apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports: 
        - containerPort: 8080
      envFrom:
        - configMapRef: 
            name: app-config    # name of config map here


# > kubectl create -f configMapInPod.yaml

---
# on more way we have
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports: 
        - containerPort: 8080
      env: 
        - name: APP_COLOR
          valueFrom: 
            configMapKeyRef:
              name: app-config
              key: APP_COLOR

# under volumes
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports: 
        - containerPort: 8080
      volumes:
        - name: app-config-names
          configMap:
            name: app-config

---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
spec:
  containers:
  - env:
    - name: APP_COLOR
      valueFrom:
       configMapKeyRef:
         name: webapp-config-map
         key: APP_COLOR
    image: kodekloud/webapp-color
    name: webapp-color