apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  label:
    app: my-app
    type: frontend
spec:
  template:
    metadata: 
      name: myapp-pod
      labels:
        app: my-app
        type: frontend
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 3

# kubectl create -f rc-definition.yaml
# kubectl get replicationcontroller
# kubectl get pods